# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "efce8db04b708625f66a5f6bc98ab582"
name = "plugin-specification-download"
handle = "plugin-specification-download"
application_url = "https://example.com/"
embedded = true

[build]
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
